routes/web.php
<?php
Route::get('/login', 'Auth\MSBLoginController@login_view')->name('login.view');
Route::post('/login', 'Auth\MSBLoginController@login')->name('login');
Route::get('/logout', 'Auth\MSBLoginController@logout');
Route::get('/welcome-mail', 'DashboardController@mail');

Route::group(['middleware' => 'auth'], function () {

    Route::resource("/activity","ActivityController");
    Route::resource("/module","ModuleController");
    Route::resource("/role","RoleController");
    Route::resource("/user","UserController");
    
    Route::get('role-access',"RoleAccessController@index")->name('role.access');
    Route::post('roleAclSetup', 'RoleAccessController@roleAclSetup');
    Route::post('roleacl', 'RoleAccessController@save');

    Route::get('user-access', 'UserAccessController@index')->name('user.access');
    Route::post('userAclSetup', 'UserAccessController@userAclSetup');
    Route::post('useracl', 'UserAccessController@save');

    Route::get('/check_permission', 'UserAccessController@check_permission')->name('login.check_permission');

    Route::get('/update_logs', ['uses'=>'DashboardController@update_logs'])->name('update_logs');    
    Route::get('/home', ['uses'=>'DashboardController@dashboard'])->name('home');	
    Route::get('/', ['uses'=>'DashboardController@dashboard'])->name('dashboard'); 
    Route::get('/dashboard', ['uses'=>'DashboardController@dashboard'])->name('dashboard');	

    Route::get('/employee/profile', ['uses'=>'EmployeeListController@my_profile'])->name('employee.my_profile');
    Route::post('/employee/profile/password/update', ['uses'=>'EmployeeListController@my_profile_password_update'])->name('employee.my_profile_password_update');

    // Manage Company
    Route::get('/company/list', ['uses'=>'CompanyInformationController@company_information_list'])->name('company_information.list');   
    Route::post('/company/new/store', ['uses'=>'CompanyInformationController@store'])->name('company_information.new.store');   
    Route::get('/company/edit/{id}', ['uses'=>'CompanyInformationController@edit'])->name('company_information.edit');
    Route::get('/company/details/{id}', ['uses'=>'CompanyInformationController@details'])->name('company_information.details');
    Route::post('/company/update', ['uses'=>'CompanyInformationController@update'])->name('company_information.update');    
    Route::get('/company/destroy/{id}', ['uses'=>'CompanyInformationController@destroy'])->name('company_information.destroy');

    Route::get('/global_settings/company/setup/{id}',['uses'=>'CompanyInformationController@global_settings_company'])->name('company_information.global_settings_company');

    // Manage Department
    Route::get('/department/list', ['uses'=>'DepartmentController@department_list'])->name('department.list');
    Route::post('/department/new/store', ['uses'=>'DepartmentController@store'])->name('department.new.store');
    Route::get('/department/edit/{id}', ['uses'=>'DepartmentController@edit'])->name('department.edit');
    Route::post('/department/update', ['uses'=>'DepartmentController@update'])->name('department.update');
    Route::get('/department/destroy/{id}', ['uses'=>'DepartmentController@destroy'])->name('department.destroy');
    
    // Manage Designation
    Route::get('/designation/list', ['uses'=>'DesignationController@designation_list'])->name('designation.list'); 
    Route::post('/designation/new/store', ['uses'=>'DesignationController@store'])->name('designation.new.store');
    Route::get('/designation/edit/{id}', ['uses'=>'DesignationController@edit'])->name('designation.edit');
    Route::post('/designation/update', ['uses'=>'DesignationController@update'])->name('designation.update');    
    Route::get('/designation/destroy/{id}', ['uses'=>'DesignationController@destroy'])->name('designation.destroy');
     
    // Manage Gender
    Route::get('/gender/list', ['uses'=>'GenderController@gender_list'])->name('gender.list'); 
    Route::post('/gender/new/store', ['uses'=>'GenderController@store'])->name('gender.new.store');
    Route::get('/gender/edit/{id}', ['uses'=>'GenderController@edit'])->name('gender.edit');
    Route::post('/gender/update', ['uses'=>'GenderController@update'])->name('gender.update');    
    Route::get('/gender/destroy/{id}', ['uses'=>'GenderController@destroy'])->name('gender.destroy');

    // Manage Work Shift 
    Route::get('/work_shift/list', ['uses'=>'EmployeeWorkShiftController@work_shift_list'])->name('work_shift.list'); 
    Route::post('/work_shift/new/store', ['uses'=>'EmployeeWorkShiftController@store'])->name('work_shift.new.store');
    Route::get('/work_shift/edit/{id}', ['uses'=>'EmployeeWorkShiftController@edit'])->name('work_shift.edit');
    Route::post('/work_shift/update', ['uses'=>'EmployeeWorkShiftController@update'])->name('work_shift.update');    
    Route::get('/work_shift/weekend/edit/{id}', ['uses'=>'EmployeeWorkShiftController@weekend_edit'])->name('work_shift.weekend.edit');
    Route::post('/work_shift/weekend/update', ['uses'=>'EmployeeWorkShiftController@weekend_update'])->name('work_shift.weekend.update');    
    Route::get('/work_shift/destroy/{id}', ['uses'=>'EmployeeWorkShiftController@destroy'])->name('work_shift.destroy');

    // Manage Weekend Holiday
    Route::get('/weekend_holiday/list', ['uses'=>'WeekendHolidayController@weekend_holiday_list'])->name('weekend_holiday.list'); 

    // Manage Employee
    Route::get('/employee/list', ['uses'=>'EmployeeListController@employee_list'])->name('employee.list');   
    Route::get('/employee/details/{id}', ['uses'=>'EmployeeListController@employee_details'])->name('employee.details');
    Route::post('/employee/update', ['uses'=>'EmployeeListController@update_employee_information'])->name('employee.information.update');    
    Route::get('/employee/new/create', ['uses'=>'EmployeeListController@new_employee'])->name('employee.new.create');   
    Route::POST('/employee/new/store', ['uses'=>'EmployeeListController@store_new_employee'])->name('employee.new.store');   
    Route::post('employee/profile/photo/update', ['uses' => 'EmployeeListController@employee_profile_photo'])->name('employee.profile.photo.update');
    Route::post('/employee/password/update', ['uses'=>'EmployeeListController@employee_password_update'])->name('employee.employee_password_update');
    Route::post('/employee/access_role/create', ['uses'=>'EmployeeListController@employee_access_role_create'])->name('employee.employee_access_role_create');
    Route::post('/employee/access_role/update', ['uses'=>'EmployeeListController@employee_access_role_update'])->name('employee.employee_access_role_update');
 
    Route::post('/employee/nominee/store', ['uses'=>'EmployeeNomineeController@employee_nominee_store'])->name('employee_nominee.store');
    Route::get('/employee/nominee/destroy/{id}', ['uses'=>'EmployeeNomineeController@employee_nominee_destroy'])->name('employee_nominee.destroy');

    Route::post('/employee/education/store', ['uses'=>'EmployeeEducationController@employee_education_store'])->name('employee_education.store');
    Route::get('/employee/education/destroy/{id}', ['uses'=>'EmployeeEducationController@employee_education_destroy'])->name('employee_education.destroy');

    Route::post('/employee/employment/store', ['uses'=>'EmployeeEmploymentController@employee_employment_store'])->name('employee_employment.store');
    Route::get('/employee/employment/destroy/{id}', ['uses'=>'EmployeeEmploymentController@employee_employment_destroy'])->name('employee_employment.destroy');

    Route::post('/employee/additional_info/store',['uses'=>'EmployeeAdditionalInfoController@employee_additional_info_store'])->name('employee_additional_info.store');
    Route::get('/employee/additional_info/destroy/{id}',['uses'=>'EmployeeAdditionalInfoController@employee_additional_info_destroy'])->name('employee_additional_info.destroy');
    
    Route::get('/employee/list/general',['uses'=>'EmployeeListController@employee_list_general'])->name('employee.list.general');   

    //Employee Attendance Management
    Route::get('/employee/attendance/history/today',['uses'=>'EmployeeAttendanceController@todays_attendance'])->name('employee.attendance.todays_attendance');   
    Route::get('/employee/attendance/history/daily_view',['uses'=>'EmployeeAttendanceController@daily_attendance_view'])->name('employee.attendance.daily_attendance_view');   
    Route::post('/employee/attendance/history/daily',['uses'=>'EmployeeAttendanceController@daily_attendance'])->name('employee.attendance.daily_attendance');   
    Route::get('/employee/attendance/import/excel',['uses'=>'EmployeeAttendanceImporterController@import_from_excel'])->name('employee.attendance.import_from_excel');   
    Route::post('/employee/attendance/import/excel/store',['uses'=>'EmployeeAttendanceImporterController@import_from_excel_store'])->name('employee.attendance.import_from_excel_store');   

    Route::get('/employee/attendance/history/date_wise_view',['uses'=>'EmployeeAttendanceController@date_wise_attendance_view'])->name('employee.attendance.date_wise_attendance_view');   
    Route::POST('/employee/attendance/history/date_wise_data',['uses'=>'EmployeeAttendanceController@date_wise_attendance_data'])->name('employee.attendance.date_wise_attendance_data');

    Route::get('/employee/attendance/history/myself',['uses'=>'EmployeeAttendanceController@myself_date_wise_attendance_view'])->name('employee.attendance.myself_date_wise_attendance_view');   
    Route::POST('/employee/attendance/history/myself_data',['uses'=>'EmployeeAttendanceController@myself_date_wise_attendance_data'])->name('employee.attendance.myself_date_wise_attendance_data');

    Route::get('/employee/attendance/give_attendance/app',['uses'=>'EmployeeAttendanceController@give_attendance_by_app'])->name('employee.attendance.give_attendance_by_app');   

resources/views/user_access_control/activity_management/create.blade.php
@extends('layout.master')
@section('title','Add New Activity')
@section('extra_css')
@endsection
@section('content')
    <div class="br-pagetitle my-pagetitle">
        <div>
            <h4> <i class="icon fa fa-plus-circle"></i> Add New Activity </h4>
        </div>

        <div class="pagetitle-btn">
            <a href="{{route('role.index')}}" class="btn  btn-info btn-sm custom-btn-1 btn-1 tx-11 tx-uppercase pd-y-8 pd-x-18 tx-mont tx-medium"> <i class="fas fa-list"></i> Activity List</a>
        </div>
    </div>
    <div class="br-pagebody br-pagebody-1">
        <div class="br-section-wrapper">
            <div class="table-wrapper">
                {!! Form::open(['method'=>'POST', 'route'=>'activity.store']) !!}
                    <div class="row">
                
                        <div class="col-sm-12">
                            <div class="form-group row">
                                <label for="form-label" class="col-sm-3 control-label form-label-1">Activity Name <span class="msb-txt-red">*</span></label>
                                <div class="col-sm-8 pl-0">
                                    <input type="text" class="form-control" name="name" autocomplete="off" placeholder="Activity Name" required="">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-12">
                            <div class="form-group row">
                                <label for="form-label" class="col-sm-3 control-label form-label-1">Description</label>
                                <div class="col-sm-8 pl-0">
                                    <textarea class="form-control" name="description" rows="4" maxlength="250" autocomplete="off" placeholder="Description" ></textarea>
                                </div>
                            </div>
                        </div>

                    </div>
                    <hr>
                    <div class="form-group text-center col-sm-12">
                        <button class="btn btn-info btn-sm custom-btn-1 ml-2" type="submit"> <i class="fa fa-save"></i> Save Information</button>
                    </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection
@section('extra_js')
@endsection

resources/views/user_access_control/activity_management/edit.blade.php
@extends('layout.master')
@section('title','Edit Activity Information')
@section('extra_css')
@endsection
@section('content')
    <div class="br-pagetitle my-pagetitle">
        <div>
            <h4> <i class="icon icon ion-ios-bookmarks-outline"></i> Edit Activity Information </h4>
        </div>

        <div class="pagetitle-btn">
            <a href="{{route('activity.index')}}" class="btn  btn-info btn-sm custom-btn-1 btn-1 tx-11 tx-uppercase pd-y-8 pd-x-18 tx-mont tx-medium"> <i class="fas fa-list"></i> Activity List</a>
        </div>
    </div>
    <div class="br-pagebody br-pagebody-1">
        <div class="br-section-wrapper">
            <div class="table-wrapper">
                
                <form method="post" action="{{route("activity.update", $activity->id)}}">
                    @method('put')
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control {{$errors->has("name") ? "is-invalid":""}}" id="name" name="name" placeholder="Enter Activity Name" value="{{old('name',$activity->name)}}">
                            <span class="text-danger"> {{$errors->has("name") ? $errors->first("name") : ""}} </span>
                        </div>

                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" id="description" name="description" placeholder="Enter Activity Description">{{old('description',$activity->description)}}</textarea>
                        </div>

                        <div class="form-group select2-parent">
                            <label>Status</label>
                            <select name="status" class="form-control single-select2" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true">
                                <option value="0" {{(old("status") == 0 || $activity->status == 0 ) ? "selected" : "" }}>Inactive</option>
                                <option value="1" {{(old("status") == 1 || $activity->status == 1 ) ? "selected" : "" }}>Active</option>
                            </select>
                        </div>
                    </div>
                    <div class="text-left">
                        <button type="submit" class="btn btn-info">Update</button>
                        <button type="button" class="btn btn-default cancel">Cancel</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
@endsection
@section('extra_js')
@endsection

resources/views/user_access_control/activity_management/list.blade.php
@extends('layout.master')
@section('title','Activity List')
@section('extra_css')
@endsection
@section('content')
    <div class="br-pagetitle my-pagetitle">
        <div>
            <h4> <i class="icon fas fa-list"></i> Activity List</h4>
        </div>

        <div class="pagetitle-btn">
            @if(!empty($aclList[5][1]))
                <a href="{{route('activity.create')}}" class="btn  btn-info btn-sm custom-btn-1 btn-1 tx-11 tx-uppercase pd-y-8 pd-x-18 tx-mont tx-medium"> <i class="fas fa-plus-circle"></i> Add New</a>
            @endif
        </div>
    </div>
    <div class="br-pagebody br-pagebody-1">
        <div class="br-section-wrapper">
            <div class="table-wrapper scrollme">
                <table id="myDatatable25" class="table table-bordered table-hover table-striped">
                    <thead>
                    <tr>
                        <th class="text-center">SL</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th class="text-center">Activity ID</th>
                        <th class="text-center">Created By</th>
                        <th class="text-center">Updated By</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($activities as $activity)
                        <tr>
                            <td class="text-center">{{$loop->iteration}}</td>
                            <td>{{ $activity->name }}</td>
                            <td>{{ $activity->description }}</td>
                            <td class="text-center">{{$activity->id}}</td>
                            <td class="text-center">{{$activity->createdBy->name ?? ''}}</td>
                            <td class="text-center">{{ $activity->updatedBy->name ?? '' }}</td>
                            <td class="text-center">
                                @if($activity->status == 1)
                                    <span class="text-primary">Active</span>
                                @else
                                    <span class="text-danger">Inactive</span>
                                @endif
                            </td>
                            <td class="text-center">
                                @if(!empty($aclList[5][3]) || !empty($aclList[5][4]))
                                    @if(!empty($aclList[5][3]))
                                        <a class="btn btn-sm btn-warning text-white" href="{{route('activity.edit', $activity->id)}}" title="Edit">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                    @endif
                                    @if(!empty($aclList[5][4]))
                                    @endif
                                @endif
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('extra_js')
@endsection